### ISSUE TITLE
Logging to external resource through js_set

### ISSUE THREAD

**Issue by AHarmlessPyro** [zongzw/nginx-njs-usecases#3]
Hi,

I was looking at  the example in [json_logging](https://github.com/zongzw-nginx/nginx-njs-usecases/blob/bb066ec50065c7bf92a4489c5ba8cb26edf450d1/json_logging/nginx.conf#L12) and was curious about the logging to the /elk endpoint mentioned in the [readme](https://github.com/zongzw-nginx/nginx-njs-usecases/tree/master/json_logging) and commented in [logging.js](https://github.com/zongzw-nginx/nginx-njs-usecases/blob/bb066ec50065c7bf92a4489c5ba8cb26edf450d1/json_logging/logging.js#L31). 

As far as I remember, it wasn't possible to perform any subrequests outside of `access_by_js/rewrite_by_js/content_by_js` stuff (and iirc, same for openresty). Is there any special feature I'm missing here ? I tried doing the same to an external endpoint (i.e. not one listed on nginx or on the same server) and while it didn't fail, the request never went out either (at least without the `detached=true` param).

**Comment by zongzw** [comment]
Sure, `r.subrequest` cannot send to external endpoints. But we can create a internal endpoint in `nginx.conf` as:

```
location /elk_endpoint {
    proxy_pass http://my_elk.logstaash_or_elastic.endpoint/;
}
``` 

I remembered that I had tried this test before.

**Comment by AHarmlessPyro** [comment]
Hey thanks! That works great. I'm sure this is well known, but could this be added to the [njs-examples](https://github.com/nginx/njs-examples) github too as a possible solution when apis need to be contacted in log/filter/set functions. Closing this issue otherwise.
